#!/usr/bin/env python3
"""Generate Android API DTOs from the shared OpenAPI; --check prevents drift."""
import json
import sys
from pathlib import Path
root = Path(__file__).resolve().parents[1]
schemas = json.loads((root / 'contracts/openapi.json').read_text())['components']['schemas']
names = ['Profile', 'Workspace', 'Session', 'BearerAuth', 'Login', 'Register', 'Acknowledgement', 'SessionList', 'Account', 'AccountCreate', 'AccountUpdate', 'AccountList', 'MutationResult', 'Transaction', 'Category', 'Tag', 'Tombstone', 'Rate', 'Entry', 'Allocation', 'AllocationInput', 'ExpenseCreate', 'IncomeCreate', 'TransactionList', 'ExpenseReplace', 'IncomeReplace', 'TransactionDelete', 'VersionExpectation']
def kotlin_type(schema):
    if 'anyOf' in schema:
        values = [x for x in schema['anyOf'] if x.get('type') != 'null']
        assert len(values) == 1
        return kotlin_type(values[0]) + '?'
    if schema.get('type') == 'array':
        return 'List<' + kotlin_type(schema['items']) + '>'
    if '$ref' in schema:
        name = schema['$ref'].split('/')[-1]
        return name if name in names else kotlin_type(schemas[name])
    if 'const' in schema:
        return 'Boolean' if isinstance(schema['const'], bool) else 'String'
    return {'string': 'String', 'boolean': 'Boolean', 'integer': 'Int'}[schema['type']]
lines = ['// Generated by scripts/generate-android-contracts.py. Do not edit.',
         'package com.capital.accounting.api', '', 'import kotlinx.serialization.Serializable', '']
for name in names:
    schema = schemas[name]
    assert set(schema['required']) == set(schema['properties'])
    lines += ['@Serializable', f'data class {name}(']
    lines += [f'    val {field}: {kotlin_type(value)},' for field, value in schema['properties'].items()]
    lines += [') {']
    checks = []
    for field, value in schema['properties'].items():
        if 'const' in value:
            checks.append(f'        require({field} == {json.dumps(value["const"])}) {{ "Invalid {name}.{field}" }}')
        if 'enum' in value:
            values = ', '.join(json.dumps(x) for x in value['enum'])
            checks.append(f'        require({field} in setOf({values})) {{ "Invalid {name}.{field}" }}')
    if checks: lines += ['    init {'] + checks + ['    }']
    lines += [f'    override fun toString() = "{name}([redacted])"', '}', '']
content = '\n'.join(lines)
path = root / 'android/app/src/main/java/com/capital/accounting/api/ApiModels.kt'
if '--check' in sys.argv:
    assert path.read_text() == content, 'Android DTOs differ from OpenAPI; regenerate'
    print('PASS Android API DTOs match shared OpenAPI')
else:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
