// Generated by scripts/generate-android-contracts.py. Do not edit.
package com.capital.accounting.api

import kotlinx.serialization.Serializable

@Serializable
data class Profile(
    val id: String,
    val email: String,
    val timezone: String,
) {
    override fun toString() = "Profile([redacted])"
}

@Serializable
data class Workspace(
    val id: String,
    val name: String,
    val version: String,
    val role: String,
    val sync_generation_id: String,
) {
    init {
        require(role in setOf("owner", "member")) { "Invalid Workspace.role" }
    }
    override fun toString() = "Workspace([redacted])"
}

@Serializable
data class Session(
    val id: String,
    val device_name: String,
    val is_current: Boolean,
    val created_at: String,
    val last_seen_at: String,
    val expires_at: String,
    val absolute_expires_at: String,
) {
    override fun toString() = "Session([redacted])"
}

@Serializable
data class BearerAuth(
    val profile: Profile,
    val workspace: Workspace,
    val session: Session,
    val transport: String,
    val access_token: String,
    val token_type: String,
) {
    init {
        require(transport == "bearer") { "Invalid BearerAuth.transport" }
        require(token_type == "Bearer") { "Invalid BearerAuth.token_type" }
    }
    override fun toString() = "BearerAuth([redacted])"
}

@Serializable
data class Login(
    val email: String,
    val password: String,
    val device_name: String,
    val transport: String,
) {
    init {
        require(transport in setOf("cookie", "bearer")) { "Invalid Login.transport" }
    }
    override fun toString() = "Login([redacted])"
}

@Serializable
data class Register(
    val email: String,
    val password: String,
    val device_name: String,
    val transport: String,
    val timezone: String,
) {
    init {
        require(transport in setOf("cookie", "bearer")) { "Invalid Register.transport" }
    }
    override fun toString() = "Register([redacted])"
}

@Serializable
data class Acknowledgement(
    val ok: Boolean,
) {
    init {
        require(ok == true) { "Invalid Acknowledgement.ok" }
    }
    override fun toString() = "Acknowledgement([redacted])"
}

@Serializable
data class SessionList(
    val items: List<Session>,
    val next_cursor: String?,
) {
    override fun toString() = "SessionList([redacted])"
}

@Serializable
data class Account(
    val id: String,
    val workspace_id: String,
    val version: String,
    val created_at: String,
    val updated_at: String,
    val deleted_at: String?,
    val name: String,
    val type: String,
    val currency: String,
    val opened_at: String,
    val archived_at: String?,
    val balance_version: String,
    val posted_balance_minor: String,
    val pending_delta_minor: String,
    val projected_balance_minor: String,
) {
    init {
        require(type in setOf("cash", "bank", "card")) { "Invalid Account.type" }
    }
    override fun toString() = "Account([redacted])"
}

@Serializable
data class AccountCreate(
    val id: String,
    val name: String,
    val type: String,
    val currency: String,
    val opened_at: String,
    val occurred_timezone: String,
    val opening_balance_minor: String,
) {
    init {
        require(type in setOf("cash", "bank", "card")) { "Invalid AccountCreate.type" }
    }
    override fun toString() = "AccountCreate([redacted])"
}

@Serializable
data class AccountUpdate(
    val expected_version: String,
    val name: String,
    val type: String,
    val archived: Boolean,
) {
    init {
        require(type in setOf("cash", "bank", "card")) { "Invalid AccountUpdate.type" }
    }
    override fun toString() = "AccountUpdate([redacted])"
}

@Serializable
data class AccountList(
    val items: List<Account>,
    val next_cursor: String?,
) {
    override fun toString() = "AccountList([redacted])"
}

@Serializable
data class MutationResult(
    val action_id: String,
    val accounts: List<Account>,
    val transactions: List<Transaction>,
    val categories: List<Category>,
    val tags: List<Tag>,
    val deleted: List<Tombstone>,
    val sync_group_sequence: String,
    val generation_id: String,
) {
    override fun toString() = "MutationResult([redacted])"
}

@Serializable
data class Transaction(
    val id: String,
    val workspace_id: String,
    val version: String,
    val created_at: String,
    val updated_at: String,
    val deleted_at: String?,
    val kind: String,
    val status: String,
    val occurred_at: String,
    val occurred_timezone: String,
    val note: String,
    val payee: String,
    val reason: String?,
    val parent_transaction_id: String?,
    val fee_transaction_id: String?,
    val rate: Rate?,
    val entries: List<Entry>,
    val allocations: List<Allocation>,
    val tag_ids: List<String>,
) {
    init {
        require(kind in setOf("opening", "expense", "income", "transfer", "refund", "adjustment")) { "Invalid Transaction.kind" }
        require(status in setOf("pending", "posted")) { "Invalid Transaction.status" }
    }
    override fun toString() = "Transaction([redacted])"
}

@Serializable
data class Category(
    val id: String,
    val workspace_id: String,
    val version: String,
    val created_at: String,
    val updated_at: String,
    val deleted_at: String?,
    val name: String,
    val archived_at: String?,
    val parent_id: String?,
) {
    override fun toString() = "Category([redacted])"
}

@Serializable
data class Tag(
    val id: String,
    val workspace_id: String,
    val version: String,
    val created_at: String,
    val updated_at: String,
    val deleted_at: String?,
    val name: String,
    val archived_at: String?,
) {
    override fun toString() = "Tag([redacted])"
}

@Serializable
data class Tombstone(
    val entity_type: String,
    val id: String,
    val workspace_id: String,
    val version: String,
    val deleted_at: String,
) {
    init {
        require(entity_type in setOf("account", "transaction", "category", "tag")) { "Invalid Tombstone.entity_type" }
    }
    override fun toString() = "Tombstone([redacted])"
}

@Serializable
data class Rate(
    val numerator: String,
    val denominator: String,
) {
    override fun toString() = "Rate([redacted])"
}

@Serializable
data class Entry(
    val id: String,
    val account_id: String,
    val currency: String,
    val amount_minor: String,
) {
    override fun toString() = "Entry([redacted])"
}

@Serializable
data class Allocation(
    val id: String,
    val category_id: String?,
    val amount_minor: String,
    val original_allocation_id: String?,
    val remaining_refundable_minor: String,
) {
    override fun toString() = "Allocation([redacted])"
}

@Serializable
data class AllocationInput(
    val id: String,
    val category_id: String?,
    val amount_minor: String,
) {
    override fun toString() = "AllocationInput([redacted])"
}

@Serializable
data class ExpenseCreate(
    val id: String,
    val occurred_at: String,
    val occurred_timezone: String,
    val note: String,
    val payee: String,
    val tag_ids: List<String>,
    val kind: String,
    val account_id: String,
    val amount_minor: String,
    val allocations: List<AllocationInput>,
) {
    init {
        require(kind == "expense") { "Invalid ExpenseCreate.kind" }
    }
    override fun toString() = "ExpenseCreate([redacted])"
}

@Serializable
data class IncomeCreate(
    val id: String,
    val occurred_at: String,
    val occurred_timezone: String,
    val note: String,
    val payee: String,
    val tag_ids: List<String>,
    val kind: String,
    val account_id: String,
    val amount_minor: String,
    val allocations: List<AllocationInput>,
) {
    init {
        require(kind == "income") { "Invalid IncomeCreate.kind" }
    }
    override fun toString() = "IncomeCreate([redacted])"
}

@Serializable
data class TransactionList(
    val items: List<Transaction>,
    val next_cursor: String?,
) {
    override fun toString() = "TransactionList([redacted])"
}
