// Generated by scripts/generate-android-contracts.py. Do not edit.
package com.capital.accounting.api

import kotlinx.serialization.Serializable

@Serializable
data class Profile(
    val id: String,
    val email: String,
    val timezone: String,
) {
    override fun toString() = "Profile([redacted])"
}

@Serializable
data class Workspace(
    val id: String,
    val name: String,
    val version: String,
    val role: String,
    val sync_generation_id: String,
) {
    init {
        require(role in setOf("owner", "member")) { "Invalid Workspace.role" }
    }
    override fun toString() = "Workspace([redacted])"
}

@Serializable
data class Session(
    val id: String,
    val device_name: String,
    val is_current: Boolean,
    val created_at: String,
    val last_seen_at: String,
    val expires_at: String,
    val absolute_expires_at: String,
) {
    override fun toString() = "Session([redacted])"
}

@Serializable
data class BearerAuth(
    val profile: Profile,
    val workspace: Workspace,
    val session: Session,
    val transport: String,
    val access_token: String,
    val token_type: String,
) {
    init {
        require(transport == "bearer") { "Invalid BearerAuth.transport" }
        require(token_type == "Bearer") { "Invalid BearerAuth.token_type" }
    }
    override fun toString() = "BearerAuth([redacted])"
}

@Serializable
data class Login(
    val email: String,
    val password: String,
    val device_name: String,
    val transport: String,
) {
    init {
        require(transport in setOf("cookie", "bearer")) { "Invalid Login.transport" }
    }
    override fun toString() = "Login([redacted])"
}

@Serializable
data class Register(
    val email: String,
    val password: String,
    val device_name: String,
    val transport: String,
    val timezone: String,
) {
    init {
        require(transport in setOf("cookie", "bearer")) { "Invalid Register.transport" }
    }
    override fun toString() = "Register([redacted])"
}

@Serializable
data class Acknowledgement(
    val ok: Boolean,
) {
    init {
        require(ok == true) { "Invalid Acknowledgement.ok" }
    }
    override fun toString() = "Acknowledgement([redacted])"
}
