events {}
http {
  resolver 127.0.0.11 valid=5s ipv6=off;
  access_log off;
  include /etc/nginx/mime.types;
  server {
    listen 443 ssl;
    set $api_backend api:8080;
    ssl_certificate /etc/nginx/tls/localhost.crt;
    ssl_certificate_key /etc/nginx/tls/localhost.key;
    root /usr/share/nginx/html;
    location /api/ {
      proxy_pass http://$api_backend;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
    }
    location /health/ { proxy_pass http://$api_backend; }
    location / { try_files $uri $uri/ /index.html; }
  }
}
