import { test, expect } from '@playwright/test';

test('real category tree, tags, exact splits, archive and immutable PUT retry', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`classification-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Кошелек');
  await page.getByLabel('Начальный остаток, EUR').fill('100,00');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts strong')).toHaveText('100,00 EUR');
  await page.getByLabel('Название категории', { exact: true }).fill('Дом');
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить категорию Дом', exact: true })).toBeVisible();
  await page.getByLabel('Название категории', { exact: true }).fill('Продукты');
  await page.getByLabel('Родительская категория').selectOption({ label: 'Дом' });
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('option', { name: 'Дом / Продукты', exact: true }).first()).toBeAttached();
  const text = '<img src=x onerror="window.accountingXss=true">';
  await page.getByLabel('Название тега', { exact: true }).fill(text);
  await page.getByRole('button', { name: 'Создать тег', exact: true }).click();
  await expect(page.getByLabel(text, { exact: true })).toBeVisible();
  await page.getByLabel('Сумма', { exact: true }).fill('10,01');
  await page.getByLabel('Категория', { exact: true }).selectOption({ label: 'Дом / Продукты' });
  await page.getByRole('button', { name: 'Добавить часть', exact: true }).click();
  await page.getByLabel('Сумма части 1').fill('4,00');
  await page.getByLabel('Сумма части 2').fill('6,00');
  await page.getByLabel('Категория части 2').selectOption({ label: 'Дом' });
  await page.getByLabel(text, { exact: true }).check();
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Сумма частей должна точно совпадать');
  await expect(page.locator('.accounts strong')).toHaveText('100,00 EUR');
  await page.getByLabel('Сумма части 2').fill('6,01');
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts strong')).toHaveText('89,99 EUR');
  await expect(page.locator('.history')).toContainText('Дом / Продукты · 4,00 EUR');
  await expect(page.locator('.history')).toContainText('Дом · 6,01 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const history = await (await context.request.get(`${root}/transactions`)).json();
  const expense = history.items.find((item: { kind: string }) => item.kind === 'expense');
  expect(expense.allocations.map((item: { amount_minor: string }) => item.amount_minor).sort()).toEqual(['400', '601']);
  expect(expense.tag_ids).toHaveLength(1);
  await page.getByRole('button', { name: 'Изменить категорию Продукты', exact: true }).click();
  await page.getByLabel('Категория в архиве').check();
  const commands: { key: string | undefined; body: string | null }[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/categories/*', async route => {
    if (route.request().method() !== 'PUT') { await route.continue(); return; }
    commands.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() });
    const response = await route.fetch();
    expect(response.status()).toBe(200);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({ response }); }
  });
  await page.getByRole('button', { name: 'Сохранить категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Повторить ту же команду', exact: true })).toBeVisible();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Повторить ту же команду', exact: true })).toHaveCount(0);
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  await expect(page.getByLabel('Категория', { exact: true }).getByRole('option', { name: 'Дом / Продукты', exact: true })).toHaveCount(0);
  await expect(page.locator('.history')).toContainText('Дом / Продукты · 4,00 EUR');
  await page.getByRole('button', { name: `Изменить тег ${text}`, exact: true }).click();
  await page.getByLabel('Тег в архиве').check();
  await page.getByRole('button', { name: 'Сохранить тег', exact: true }).click();
  await expect(page.getByLabel(text, { exact: true })).toHaveCount(0);
  await expect(page.locator('.history')).toContainText(text);
  await expect(page.locator('img')).toHaveCount(0);
  expect(await page.evaluate(() => Reflect.get(window, 'accountingXss'))).toBeUndefined();
  await page.getByRole('button', { name: 'Изменить категорию Продукты', exact: true }).click();
  await page.getByLabel('Категория в архиве').uncheck();
  await page.getByRole('button', { name: 'Сохранить категорию', exact: true }).click();
  await expect(page.getByLabel('Категория', { exact: true }).getByRole('option', { name: 'Дом / Продукты', exact: true })).toBeAttached();
  await expect(page.locator('.accounts strong')).toHaveText('89,99 EUR');
});

test('real transfer keeps exact balances and survives reload', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`transfer-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  for (const name of ['Основной', 'Резерв']) {
    await page.getByLabel('Название счета').fill(name);
    await page.getByLabel('Начальный остаток, EUR').fill('100,00');
    await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
    await expect(page.locator('.accounts')).toContainText(name);
  }
  await page.getByLabel('Со счета', { exact: true }).selectOption({ label: 'Основной · EUR' });
  await page.getByLabel('На счет', { exact: true }).selectOption({ label: 'Резерв · EUR' });
  await page.getByLabel('Сумма списания, EUR').fill('10,01');
  await page.getByRole('button', { name: 'Сохранить перевод', exact: true }).click();
  await expect(page.locator('.accounts li').filter({ hasText: 'Основной' })).toContainText('89,99 EUR');
  await expect(page.locator('.accounts li').filter({ hasText: 'Резерв' })).toContainText('110,01 EUR');
  await page.reload();
  await expect(page.locator('.history')).toContainText('Перевод');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const history = await (await context.request.get(`/api/v1/workspaces/${auth.workspace.id}/transactions`)).json();
  expect(history.items.filter((t: {kind: string}) => t.kind === 'transfer')).toHaveLength(1);
  expect(history.items.filter((t: {kind: string}) => ['income', 'expense'].includes(t.kind))).toHaveLength(0);
});

test('FX transfer and third-currency fee commit once after lost response', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`fx-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  for (const [currency, name, type] of [['EUR', 'Евро', 'bank'], ['USD', 'Доллары', 'card'], ['KWD', 'Комиссии', 'cash']]) {
    await page.getByLabel('Название счета').fill(name);
    await page.getByLabel('Валюта счета', { exact: true }).selectOption(currency);
    await page.getByLabel('Тип счета', { exact: true }).selectOption(type);
    await page.getByLabel(`Начальный остаток, ${currency}`).fill('100');
    await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
    await expect(page.locator('.accounts')).toContainText(name);
  }
  await page.getByLabel('Со счета', { exact: true }).selectOption({ label: 'Евро · EUR' });
  await page.getByLabel('На счет', { exact: true }).selectOption({ label: 'Доллары · USD' });
  await page.getByLabel('Сумма списания, EUR').fill('3');
  await page.getByLabel('Сумма зачисления, USD').fill('1');
  await page.getByLabel('Добавить комиссию', { exact: true }).check();
  await page.getByLabel('Счет комиссии', { exact: true }).selectOption({ label: 'Комиссии · KWD' });
  await page.getByLabel('Комиссия, KWD', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Сохранить перевод', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Комиссия должна быть больше нуля');
  await expect(page.locator('.accounts li').filter({ hasText: 'Евро' })).toContainText('100,00 EUR');
  await page.getByLabel('Комиссия, KWD', { exact: true }).fill('0,123');
  const commands: { key: string | undefined; body: string | null }[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/transactions', async route => {
    if (route.request().method() !== 'POST') { await route.continue(); return; }
    commands.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() });
    const response = await route.fetch();
    expect(response.status()).toBe(201);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({ response }); }
  });
  await page.getByRole('button', { name: 'Сохранить перевод', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  for (const [name, balance] of [['Евро', '97,00 EUR'], ['Доллары', '101,00 USD'], ['Комиссии', '99,877 KWD']]) {
    await expect(page.locator('.accounts li').filter({ hasText: name })).toContainText(balance);
  }
  await expect(page.locator('.history')).toContainText('Комиссия перевода');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const history = await (await context.request.get(`${root}/transactions`)).json();
  const transfers = history.items.filter((t: {kind: string}) => t.kind === 'transfer');
  const fees = history.items.filter((t: {kind: string}) => t.kind === 'expense');
  expect(transfers).toHaveLength(1); expect(fees).toHaveLength(1);
  expect(transfers[0].rate).toEqual({ numerator: '1', denominator: '3' });
  expect(transfers[0].fee_transaction_id).toBe(fees[0].id);
  expect(fees[0].parent_transaction_id).toBe(transfers[0].id);
  expect(fees[0].allocations[0].amount_minor).toBe('123');
  const accounts = await (await context.request.get(`${root}/accounts`)).json();
  expect(accounts.items.find((a: {name: string}) => a.name === 'Доллары').type).toBe('card');
  expect(accounts.items.find((a: {name: string}) => a.name === 'Комиссии').type).toBe('cash');
  await page.getByRole('button', { name: `Изменить операцию ${transfers[0].id}`, exact: true }).click();
  const transferEditor = page.getByRole('heading', { name: 'Изменить перевод', exact: true }).locator('..');
  await transferEditor.getByLabel('Сумма списания, EUR').fill('6');
  await transferEditor.getByLabel('Сумма зачисления, USD').fill('2');
  await transferEditor.getByLabel('Комиссия, KWD', { exact: true }).fill('0,246');
  await transferEditor.getByRole('button', { name: 'Добавить часть комиссии', exact: true }).click();
  await transferEditor.getByLabel('Сумма части комиссии 1').fill('0,100');
  await transferEditor.getByLabel('Сумма части комиссии 2').fill('0,146');
  await transferEditor.getByRole('button', { name: 'Сохранить изменения перевода', exact: true }).click();
  await expect(transferEditor).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({ hasText: 'Евро' })).toContainText('94,00 EUR');
  await expect(page.locator('.accounts li').filter({ hasText: 'Доллары' })).toContainText('102,00 USD');
  await expect(page.locator('.accounts li').filter({ hasText: 'Комиссии' })).toContainText('99,754 KWD');
  const replaced = await (await context.request.get(`${root}/transactions/${transfers[0].id}`)).json();
  const replacedFee = await (await context.request.get(`${root}/transactions/${fees[0].id}`)).json();
  expect(replaced.fee_transaction_id).toBe(fees[0].id);
  expect(replacedFee.allocations.map((p: {id: string}) => p.id)).toContain(fees[0].allocations[0].id);
  expect(replacedFee.allocations).toHaveLength(2);
  expect(replaced.entries.map((e: {id: string}) => e.id).sort()).toEqual(transfers[0].entries.map((e: {id: string}) => e.id).sort());
  await page.getByRole('button', { name: `Изменить операцию ${fees[0].id}`, exact: true }).click();
  const feeEditor = page.getByRole('heading', { name: 'Изменить операцию', exact: true }).locator('..');
  await feeEditor.getByLabel('Сумма', { exact: true }).fill('0,300');
  await feeEditor.getByLabel('Сумма части 1').fill('0,100');
  await feeEditor.getByLabel('Сумма части 2').fill('0,200');
  await feeEditor.getByRole('button', { name: 'Сохранить изменения операции', exact: true }).click();
  await expect(feeEditor).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({ hasText: 'Комиссии' })).toContainText('99,700 KWD');
  const parentAfterFee = await (await context.request.get(`${root}/transactions/${transfers[0].id}`)).json();
  expect(BigInt(parentAfterFee.version)).toBe(BigInt(replaced.version) + 1n);
  await page.getByRole('button', { name: `Изменить операцию ${transfers[0].id}`, exact: true }).click();
  await transferEditor.getByLabel('Добавить комиссию', { exact: true }).uncheck();
  await transferEditor.getByRole('button', { name: 'Сохранить изменения перевода', exact: true }).click();
  await expect(transferEditor).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({ hasText: 'Комиссии' })).toContainText('100,000 KWD');
  const withoutFee = await (await context.request.get(`${root}/transactions/${transfers[0].id}`)).json();
  expect(withoutFee.fee_transaction_id).toBeNull();
  await page.getByRole('button', { name: `Изменить операцию ${transfers[0].id}`, exact: true }).click();
  await transferEditor.getByLabel('Добавить комиссию', { exact: true }).check();
  await transferEditor.getByLabel('Счет комиссии', { exact: true }).selectOption({ label: 'Комиссии · KWD' });
  await transferEditor.getByLabel('Комиссия, KWD', { exact: true }).fill('0,100');
  await transferEditor.getByRole('button', { name: 'Сохранить изменения перевода', exact: true }).click();
  await expect(transferEditor).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({ hasText: 'Комиссии' })).toContainText('99,900 KWD');
  const withNewFee = await (await context.request.get(`${root}/transactions/${transfers[0].id}`)).json();
  expect(withNewFee.fee_transaction_id).not.toBe(fees[0].id);
  await page.getByRole('button', { name: `Удалить операцию ${transfers[0].id}`, exact: true }).click();
  const deletion = page.getByRole('heading', { name: 'Удаление операции', exact: true }).locator('..');
  await expect(deletion).toContainText('Комиссия будет удалена вместе с переводом');
  await deletion.getByRole('button', { name: 'Подтвердить удаление операции', exact: true }).click();
  await expect(deletion).toHaveCount(0);
  for (const [name, balance] of [['Евро', '100,00 EUR'], ['Доллары', '100,00 USD'], ['Комиссии', '100,000 KWD']]) {
    await expect(page.locator('.accounts li').filter({ hasText: name })).toContainText(balance);
  }
  expect((await context.request.get(`${root}/transactions/${transfers[0].id}`)).status()).toBe(404);
  expect((await context.request.get(`${root}/transactions/${withNewFee.fee_transaction_id}`)).status()).toBe(404);


});

test('expense editor preserves parts, retries PUT and rejects stale versions', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`editor-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Редактор');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  await page.getByLabel('Сумма', { exact: true }).fill('10');
  await page.getByLabel('Примечание', { exact: true }).fill('Редактируемый расход');
  await page.getByRole('button', { name: 'Добавить часть', exact: true }).click();
  await page.getByLabel('Сумма части 1').fill('4');
  await page.getByLabel('Сумма части 2').fill('6');
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('90,00 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const before = (await (await context.request.get(`${root}/transactions`)).json()).items.find((t: {kind: string}) => t.kind === 'expense');
  await page.getByRole('button', { name: 'Изменить операцию Редактируемый расход', exact: true }).click();
  const editor = page.getByRole('heading', { name: 'Изменить операцию', exact: true }).locator('..');
  await expect(editor.getByLabel('Тип операции', { exact: true })).toBeDisabled();
  await editor.getByLabel('Сумма', { exact: true }).fill('12');
  await editor.getByLabel('Сумма части 1').fill('4');
  await editor.getByLabel('Сумма части 2').fill('8');
  const commands: { key: string | undefined; body: string | null }[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/transactions/*', async route => {
    if (route.request().method() !== 'PUT') { await route.continue(); return; }
    commands.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() });
    const response = await route.fetch();
    expect(response.status()).toBe(200);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({ response }); }
  });
  await editor.getByRole('button', { name: 'Сохранить изменения операции', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  const after = await (await context.request.get(`${root}/transactions/${before.id}`)).json();
  expect(after.allocations.map((p: {id: string}) => p.id).sort()).toEqual(before.allocations.map((p: {id: string}) => p.id).sort());
  expect(after.entries[0].id).toBe(before.entries[0].id);
  expect(after.occurred_at).toBe(before.occurred_at);
  await expect(page.locator('.accounts')).toContainText('88,00 EUR');
  await page.unroute('**/api/v1/workspaces/*/transactions/*');
  await page.getByRole('button', { name: 'Изменить операцию Редактируемый расход', exact: true }).click();
  await expect(editor.getByLabel('Сумма', { exact: true })).toHaveValue('12.00');
  const body = { ...JSON.parse(commands[0].body!), expected_version: after.version, note: 'Правка другого устройства' };
  const concurrent = await context.request.put(`${root}/transactions/${before.id}`, { headers: { Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID() }, data: body });
  expect(concurrent.status()).toBe(200);
  await editor.getByLabel('Примечание', { exact: true }).fill('Моя устаревшая правка');
  await editor.getByRole('button', { name: 'Сохранить изменения операции', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  const final = await (await context.request.get(`${root}/transactions/${before.id}`)).json();
  expect(final.note).toBe('Правка другого устройства');
  await expect(editor.getByLabel('Примечание', { exact: true })).toHaveValue('Моя устаревшая правка');
  const comparison = page.getByRole('heading', { name: 'Конфликт операции', exact: true }).locator('..');
  await expect(comparison).toContainText('Моя устаревшая правка');
  await expect(comparison).toContainText('Правка другого устройства');
  await comparison.getByRole('button', { name: 'Загрузить серверную версию в редактор', exact: true }).click();
  await expect(comparison).toHaveCount(0);
  await expect(editor.getByLabel('Примечание', { exact: true })).toHaveValue('Правка другого устройства');
  await editor.getByRole('button', { name: 'Отменить редактирование', exact: true }).click();
  const creator = page.getByRole('heading', { name: 'Новая операция', exact: true }).locator('..');
  await creator.getByLabel('Тип операции', { exact: true }).selectOption('income');
  await creator.getByLabel('Сумма', { exact: true }).fill('5');
  await creator.getByLabel('Примечание', { exact: true }).fill('Редактируемый доход');
  await creator.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('93,00 EUR');
  await page.getByRole('button', { name: 'Изменить операцию Редактируемый доход', exact: true }).click();
  await editor.getByLabel('Сумма', { exact: true }).fill('7');
  await editor.getByRole('button', { name: 'Сохранить изменения операции', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await expect(page.locator('.accounts')).toContainText('95,00 EUR');

});

test('account archive keeps history and balances, restore enables new writes', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`archive-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Сохраняемый');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  await page.getByLabel('Сумма', { exact: true }).fill('10');
  await page.getByLabel('Примечание', { exact: true }).fill('Исторический расход');
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('90,00 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const before = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  await page.getByRole('button', { name: 'Изменить счет Сохраняемый', exact: true }).click();
  await page.getByLabel('Новое название счета').fill('Архивный');
  await page.getByLabel('Тип выбранного счета', { exact: true }).selectOption('cash');
  await page.getByLabel('Счет в архиве', { exact: true }).check();
  await page.getByRole('button', { name: 'Сохранить счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('Архивный · В архиве');
  await expect(page.locator('.accounts')).toContainText('90,00 EUR');
  await expect(page.getByRole('heading', { name: 'Новая операция' }).locator('..').getByRole('option', { name: 'Архивный · EUR', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Сохранить операцию', exact: true })).toBeDisabled();
  await expect(page.locator('.history')).toContainText('Исторический расход');
  await expect(page.locator('.history')).toContainText('Архивный · −10,00 EUR');
  const archived = await (await context.request.get(`${root}/accounts/${before.id}`)).json();
  expect(archived.archived_at).not.toBeNull(); expect(archived.type).toBe('cash');
  expect(archived.balance_version).toBe(before.balance_version);
  expect(archived.posted_balance_minor).toBe(before.posted_balance_minor);
  await page.reload();
  await page.getByRole('button', { name: 'Изменить счет Архивный', exact: true }).click();
  await page.getByLabel('Счет в архиве', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Сохранить счет', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Сохранить операцию', exact: true })).toBeEnabled();
  await expect(page.locator('.accounts')).not.toContainText('В архиве');
  await page.getByLabel('Сумма', { exact: true }).fill('1');
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('89,00 EUR');
});

test('device revoke retries after lost response and invalidates the other cookie', async ({ page, context, browser }) => {
  const email = `devices-${crypto.randomUUID()}@example.test`, password = 'synthetic-browser-password-2026';
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(email);
  await page.getByLabel('Пароль', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByText('Текущее устройство', { exact: true })).toBeVisible();
  const other = await browser.newContext({ ignoreHTTPSErrors: true });
  try {
    const device = '<img src=x onerror="window.accountingXss=true">';
    const login = await other.request.post('https://localhost:8444/api/v1/auth/login', { headers: { Origin: 'https://localhost:8444' }, data: { email, password, device_name: device, transport: 'cookie' } });
    expect(login.status()).toBe(200);
    const auth = await login.json();
    expect((await other.request.get('https://localhost:8444/api/v1/currencies')).status()).toBe(200);
    await page.getByRole('button', { name: 'Обновить устройства', exact: true }).click();
    const row = page.getByTestId(`session-${auth.session.id}`);
    await expect(row).toContainText(device);
    await expect(page.locator('img')).toHaveCount(0);
    let dropped = false;
    const ids: string[] = [];
    await page.route('**/api/v1/sessions/*', async route => {
      if (route.request().method() !== 'DELETE') { await route.continue(); return; }
      ids.push(route.request().url());
      const response = await route.fetch();
      expect(response.status()).toBe(200);
      if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
      else await route.fulfill({ response });
    });
    await row.getByRole('button', { name: `Отключить устройство ${device}`, exact: true }).click();
    await expect(page.getByRole('button', { name: 'Повторить отзыв устройства', exact: true })).toBeVisible();
    expect((await other.request.get('https://localhost:8444/api/v1/currencies')).status()).toBe(401);
    await page.getByRole('button', { name: 'Повторить отзыв устройства', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Повторить отзыв устройства', exact: true })).toHaveCount(0);
    await expect(row).toHaveCount(0);
    expect(ids).toHaveLength(2); expect(ids[1]).toBe(ids[0]);
    expect((await context.request.get('/api/v1/auth/session')).status()).toBe(200);
    await page.unroute('**/api/v1/sessions/*');
    await page.getByRole('button', { name: 'Отключить устройство Веб-браузер (текущее)', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Войти', exact: true })).toBeVisible();
    expect((await context.request.get('/api/v1/auth/session')).status()).toBe(401);
  } finally { await other.close(); }
});

test('history pages and combined filters read the real ledger', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`history-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('История');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  await page.getByLabel('Название категории', { exact: true }).fill('Покупки');
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить категорию Покупки', exact: true })).toBeVisible();
  await page.getByLabel('Название тега', { exact: true }).fill('Четные');
  await page.getByRole('button', { name: 'Создать тег', exact: true }).click();
  await expect(page.getByLabel('Четные', { exact: true })).toBeVisible();
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const account = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  const category = (await (await context.request.get(`${root}/categories`)).json()).items[0];
  const tag = (await (await context.request.get(`${root}/tags`)).json()).items[0];
  for (let i = 0; i < 12; i++) {
    const response = await context.request.post(`${root}/transactions`, { headers: { Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID() }, data: { id: crypto.randomUUID(), kind: 'expense', account_id: account.id, amount_minor: '100', occurred_at: new Date().toISOString(), occurred_timezone: 'UTC', note: `Покупка ${i + 1}`, payee: '', tag_ids: i % 2 === 0 ? [tag.id] : [], allocations: [{ id: crypto.randomUUID(), category_id: category.id, amount_minor: '100' }] } });
    expect(response.status()).toBe(201);
  }
  await page.getByRole('button', { name: 'Обновить', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('88,00 EUR');
  const history = page.getByRole('heading', { name: 'История операций', exact: true }).locator('..');
  await history.getByLabel('Тип в истории', { exact: true }).selectOption('expense');
  await history.getByLabel('Поиск в истории', { exact: true }).fill('Покупка');
  await history.getByLabel('Операций на странице', { exact: true }).selectOption('10');
  await history.getByRole('button', { name: 'Применить фильтры', exact: true }).click();
  await expect(history.locator('.history > li')).toHaveCount(10);
  await history.getByRole('button', { name: 'Загрузить еще операции', exact: true }).click();
  await expect(history.locator('.history > li')).toHaveCount(12);
  expect(new Set(await history.locator('.history > li').evaluateAll(rows => rows.map(row => row.getAttribute('data-testid')))).size).toBe(12);
  await expect(history.getByRole('button', { name: 'Загрузить еще операции', exact: true })).toHaveCount(0);
  await history.getByLabel('Счет истории', { exact: true }).selectOption(account.id);
  await history.getByLabel('Категория истории', { exact: true }).selectOption(category.id);
  await history.getByLabel('Тег истории', { exact: true }).selectOption(tag.id);
  const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; });
  await history.getByLabel('С даты', { exact: true }).fill(today);
  await history.getByLabel('По дату включительно', { exact: true }).fill(today);
  await history.getByRole('button', { name: 'Применить фильтры', exact: true }).click();
  await expect(history.locator('.history > li')).toHaveCount(6);
  await history.getByLabel('Статус в истории', { exact: true }).selectOption('pending');
  await history.getByRole('button', { name: 'Применить фильтры', exact: true }).click();
  await expect(history.getByText('Операций по выбранным условиям нет.', { exact: true })).toBeVisible();
  await history.getByRole('button', { name: 'Сбросить фильтры', exact: true }).click();
  await expect(history.locator('.history > li')).toHaveCount(13);
});

test('partial refund inherits archived categories, retries once and retains part IDs on edit', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`refund-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Возвраты');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  await page.getByLabel('Название категории', { exact: true }).fill('Старая категория');
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить категорию Старая категория', exact: true })).toBeVisible();
  await page.getByLabel('Сумма', { exact: true }).fill('10');
  await page.getByLabel('Категория', { exact: true }).selectOption({ label: 'Старая категория' });
  await page.getByRole('button', { name: 'Добавить часть', exact: true }).click();
  await page.getByLabel('Сумма части 1').fill('4');
  await page.getByLabel('Сумма части 2').fill('6');
  await page.getByLabel('Примечание', { exact: true }).fill('Исходная покупка');
  await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('90,00 EUR');
  await page.getByRole('button', { name: 'Изменить категорию Старая категория', exact: true }).click();
  await page.getByLabel('Категория в архиве').check();
  await page.getByRole('button', { name: 'Сохранить категорию', exact: true }).click();
  await expect(page.getByLabel('Категория', { exact: true }).getByRole('option', { name: 'Старая категория', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Возврат по операции Исходная покупка', exact: true }).click();
  const form = page.getByRole('heading', { name: 'Новый возврат', exact: true }).locator('..');
  await form.getByLabel('Возврат части 1').fill('100');
  await form.getByRole('button', { name: 'Сохранить возврат', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('не превышать доступный остаток');
  await form.getByLabel('Возврат части 1').fill('2');
  await form.getByLabel('Возврат части 2').fill('3');
  await form.getByLabel('Описание возврата', { exact: true }).fill('Частичный возврат');
  const commands: { key: string | undefined; body: string | null }[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/transactions', async route => {
    if (route.request().method() !== 'POST') { await route.continue(); return; }
    commands.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() });
    const response = await route.fetch(); expect(response.status()).toBe(201);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({ response }); }
  });
  await form.getByRole('button', { name: 'Сохранить возврат', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  await expect(page.locator('.accounts')).toContainText('95,00 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const history = (await (await context.request.get(`${root}/transactions`)).json()).items;
  const refund = history.find((t: {kind: string}) => t.kind === 'refund');
  const expense = history.find((t: {kind: string}) => t.kind === 'expense');
  expect(history.filter((t: {kind: string}) => t.kind === 'refund')).toHaveLength(1);
  for (const allocation of refund.allocations) {
    expect(allocation.category_id).toBe(expense.allocations.find((p: {id: string}) => p.id === allocation.original_allocation_id).category_id);
  }
  await page.getByRole('button', { name: 'Изменить операцию Частичный возврат', exact: true }).click();
  const editor = page.getByRole('heading', { name: 'Изменить возврат', exact: true }).locator('..');
  await editor.getByLabel('Возврат части 1').fill('1');
  await editor.getByLabel('Возврат части 2').fill('2');
  await editor.getByRole('button', { name: 'Сохранить изменения возврата', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await expect(page.locator('.accounts')).toContainText('93,00 EUR');
  const after = await (await context.request.get(`${root}/transactions/${refund.id}`)).json();
  expect(after.allocations.map((p: {id: string}) => p.id).sort()).toEqual(refund.allocations.map((p: {id: string}) => p.id).sort());
  const parent = await (await context.request.get(`${root}/transactions/${expense.id}`)).json();
  expect(parent.allocations.reduce((sum: bigint, p: {remaining_refundable_minor: string}) => sum + BigInt(p.remaining_refundable_minor), 0n)).toBe(700n);
  await page.getByRole('button', { name: 'Удалить операцию Исходная покупка', exact: true }).click();
  const deletion = page.getByRole('heading', { name: 'Удаление операции', exact: true }).locator('..');
  await deletion.getByRole('button', { name: 'Подтвердить удаление операции', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  expect((await context.request.get(`${root}/transactions/${expense.id}`)).status()).toBe(200);
  await expect(page.locator('.accounts')).toContainText('93,00 EUR');
  await deletion.getByRole('button', { name: 'Отменить удаление', exact: true }).click();
  const deletions: {key: string | undefined; body: string | null}[] = [];
  let deleteDropped = false, deleteReplayed = false;
  await page.route('**/api/v1/workspaces/*/transactions/*', async route => {
    if (route.request().method() !== 'DELETE') { await route.continue(); return; }
    deletions.push({key: route.request().headers()['idempotency-key'], body: route.request().postData()});
    const response = await route.fetch(); expect(response.status()).toBe(200);
    if (!deleteDropped) { deleteDropped = true; await route.abort('connectionfailed'); }
    else { deleteReplayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({response}); }
  });
  await page.getByRole('button', { name: 'Удалить операцию Частичный возврат', exact: true }).click();
  await deletion.getByRole('button', { name: 'Подтвердить удаление операции', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => deleteReplayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(deletions).toHaveLength(2); expect(deletions[1]).toEqual(deletions[0]);
  await expect(page.locator('.accounts')).toContainText('90,00 EUR');
  expect((await context.request.get(`${root}/transactions/${refund.id}`)).status()).toBe(404);
  const released = await (await context.request.get(`${root}/transactions/${expense.id}`)).json();
  expect(released.allocations.reduce((sum: bigint, p: {remaining_refundable_minor: string}) => sum + BigInt(p.remaining_refundable_minor), 0n)).toBe(1000n);
  await page.unroute('**/api/v1/workspaces/*/transactions/*');
  await page.getByRole('button', { name: 'Удалить операцию Исходная покупка', exact: true }).click();
  await deletion.getByRole('button', { name: 'Подтвердить удаление операции', exact: true }).click();
  await expect(deletion).toHaveCount(0);
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');

});

test('adjustment rejects stale balance and retries the same target after reload', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`adjustment-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Сверка');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  await page.getByLabel('Фактический остаток, EUR').fill('80');
  await page.getByLabel('Причина корректировки', { exact: true }).fill('Сверка наличных');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const account = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  const income = await context.request.post(`${root}/transactions`, { headers: { Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID() }, data: { id: crypto.randomUUID(), kind: 'income', account_id: account.id, amount_minor: '100', occurred_at: new Date().toISOString(), occurred_timezone: 'UTC', note: '', payee: '', tag_ids: [], allocations: [{ id: crypto.randomUUID(), category_id: null, amount_minor: '100' }] } });
  expect(income.status()).toBe(201);
  await page.getByRole('button', { name: 'Сохранить корректировку', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  const staleHistory = (await (await context.request.get(`${root}/transactions`)).json()).items;
  expect(staleHistory.filter((t: {kind: string}) => t.kind === 'adjustment')).toHaveLength(0);
  await page.getByRole('button', { name: 'Обновить', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('101,00 EUR');
  await page.getByLabel('Фактический остаток, EUR').fill('80');
  await page.getByLabel('Примечание корректировки', { exact: true }).fill('Проверенная корректировка');
  const commands: { key: string | undefined; body: string | null }[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/accounts/*/adjustments', async route => {
    commands.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() });
    const response = await route.fetch(); expect(response.status()).toBe(201);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({ response }); }
  });
  await page.getByRole('button', { name: 'Сохранить корректировку', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  await expect(page.locator('.accounts')).toContainText('80,00 EUR');
  const history = (await (await context.request.get(`${root}/transactions`)).json()).items;
  const adjustments = history.filter((t: {kind: string}) => t.kind === 'adjustment');
  expect(adjustments).toHaveLength(1); expect(adjustments[0].entries[0].amount_minor).toBe('-2100');
  const beforeMetadata = await (await context.request.get(`${root}/accounts/${account.id}`)).json();
  await page.getByRole('button', { name: 'Изменить операцию Проверенная корректировка', exact: true }).click();
  const editor = page.getByRole('heading', { name: 'Изменить примечание корректировки', exact: true }).locator('..');
  await editor.getByLabel('Примечание корректировки', { exact: true }).fill('Уточненное описание');
  await editor.getByRole('button', { name: 'Сохранить примечание корректировки', exact: true }).click();
  await expect(editor).toHaveCount(0);
  const final = await (await context.request.get(`${root}/transactions/${adjustments[0].id}`)).json();
  const afterMetadata = await (await context.request.get(`${root}/accounts/${account.id}`)).json();
  expect(final.reason).toBe('Сверка наличных'); expect(final.note).toBe('Уточненное описание');
  expect(final.entries).toEqual(adjustments[0].entries); expect(afterMetadata.balance_version).toBe(beforeMetadata.balance_version);
});

test('bulk classification rejects the whole stale package and replays one atomic write', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`bulk-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Пакет');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  for (let i = 1; i <= 2; i++) {
    await page.getByLabel('Сумма', { exact: true }).fill('1');
    await page.getByLabel('Примечание', { exact: true }).fill(`Пакет ${i}`);
    await page.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
    await expect(page.locator('.accounts')).toContainText(`${100 - i},00 EUR`);
  }
  await page.getByLabel('Название категории', { exact: true }).fill('Массовая категория');
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить категорию Массовая категория', exact: true })).toBeVisible();
  await page.getByLabel('Название тега', { exact: true }).fill('Пакетный');
  await page.getByRole('button', { name: 'Создать тег', exact: true }).click();
  await expect(page.getByLabel('Пакетный', { exact: true })).toBeVisible();
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const source = (await (await context.request.get(`${root}/transactions`)).json()).items.filter((t: {kind: string}) => t.kind === 'expense');
  const accountBefore = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  await page.getByLabel('Выбрать операцию Пакет 1', { exact: true }).check();
  await page.getByLabel('Выбрать операцию Пакет 2', { exact: true }).check();
  await page.getByLabel('Категория выбранных операций', { exact: true }).selectOption({ label: 'Массовая категория' });
  await page.getByLabel('Массовый тег Пакетный', { exact: true }).check();
  const changed = source[0];
  const concurrent = await context.request.put(`${root}/transactions/${changed.id}`, { headers: { Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID() }, data: { kind: 'expense', expected_version: changed.version, expected_parent_version: null, account_id: changed.entries[0].account_id, amount_minor: '100', occurred_at: changed.occurred_at, occurred_timezone: changed.occurred_timezone, note: 'Чужая правка пакета', payee: '', allocations: changed.allocations.map((p: {id: string}) => ({id: p.id, category_id: null, amount_minor: '100'})), tag_ids: [] } });
  expect(concurrent.status()).toBe(200);
  await page.getByRole('button', { name: 'Применить ко всем выбранным', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  const rejected = (await (await context.request.get(`${root}/transactions`)).json()).items.filter((t: {kind: string}) => t.kind === 'expense');
  for (const transaction of rejected) {
    expect(transaction.allocations[0].category_id).toBeNull(); expect(transaction.tag_ids).toEqual([]);
    const original = source.find((t: {id: string}) => t.id === transaction.id);
    expect(BigInt(transaction.version)).toBe(BigInt(original.version) + (transaction.id === changed.id ? 1n : 0n));
  }
  const comparison = page.getByRole('heading', { name: 'Конфликт массовой классификации', exact: true }).locator('..');
  await expect(comparison).toContainText('Чужая правка пакета');
  await expect(comparison).toContainText('Массовая категория');
  await expect(comparison).toContainText('Без категории');
  await comparison.getByRole('button', { name: 'Обновить историю и снять выбор', exact: true }).click();
  await expect(comparison).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Массовая классификация', exact: true })).toHaveCount(0);
  for (const transaction of rejected) await page.getByTestId(`transaction-${transaction.id}`).getByRole('checkbox').check();
  await page.getByLabel('Категория выбранных операций', { exact: true }).selectOption({ label: 'Массовая категория' });
  await page.getByLabel('Массовый тег Пакетный', { exact: true }).check();
  const commands: {key: string | undefined; body: string | null}[] = [];
  let dropped = false, replayed = false;
  await page.route('**/api/v1/workspaces/*/transactions/classification', async route => {
    commands.push({key: route.request().headers()['idempotency-key'], body: route.request().postData()});
    const response = await route.fetch(); expect(response.status()).toBe(200);
    if (!dropped) { dropped = true; await route.abort('connectionfailed'); }
    else { replayed = response.headers()['idempotency-replayed'] === 'true'; await route.fulfill({response}); }
  });
  await page.getByRole('button', { name: 'Применить ко всем выбранным', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Операция могла сохраниться');
  await page.reload();
  await page.getByRole('button', { name: 'Повторить ту же команду', exact: true }).click();
  await expect.poll(() => replayed).toBe(true);
  await expect(page.getByRole('heading', { name: 'Команда ожидает подтверждения' })).toHaveCount(0);
  expect(commands).toHaveLength(2); expect(commands[1]).toEqual(commands[0]);
  const final = (await (await context.request.get(`${root}/transactions`)).json()).items.filter((t: {kind: string}) => t.kind === 'expense');
  const category = (await (await context.request.get(`${root}/categories`)).json()).items[0];
  const tag = (await (await context.request.get(`${root}/tags`)).json()).items[0];
  for (const transaction of final) {
    expect(transaction.allocations[0].category_id).toBe(category.id); expect(transaction.tag_ids).toEqual([tag.id]);
    expect(BigInt(transaction.version)).toBe(BigInt(rejected.find((t: {id: string}) => t.id === transaction.id).version) + 1n);
  }
  const accountAfter = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  expect(accountAfter.balance_version).toBe(accountBefore.balance_version);
  expect(accountAfter.posted_balance_minor).toBe('9800');
});

test('historical dates and archived transfer/fee metadata survive editing', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`metadata-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  const dates = await page.evaluate(() => {
    const format = (d: Date) => { const two = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${two(d.getMonth() + 1)}-${two(d.getDate())}T${two(d.getHours())}:${two(d.getMinutes())}:${two(d.getSeconds())}.${String(d.getMilliseconds()).padStart(3, '0')}`; };
    const now = Date.now(); return [3, 2, 1].map(days => {const d = new Date(now - days * 86400000); d.setMilliseconds(123); return {local: format(d), iso: d.toISOString()};});
  });
  for (const [currency, name] of [['EUR', 'Исторический EUR'], ['KWD', 'Исторический KWD']]) {
    await page.getByLabel('Название счета').fill(name);
    await page.getByLabel('Валюта счета', { exact: true }).selectOption(currency);
    await page.getByLabel(`Начальный остаток, ${currency}`).fill('100');
    await page.getByLabel('Дата открытия счета', { exact: true }).fill(dates[0].local);
    await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
    await expect(page.locator('.accounts')).toContainText(name);
  }
  await page.getByLabel('Название категории', { exact: true }).fill('Комиссионные');
  await page.getByRole('button', { name: 'Создать категорию', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить категорию Комиссионные', exact: true })).toBeVisible();
  await page.getByLabel('Название тега', { exact: true }).fill('Метаданные');
  await page.getByRole('button', { name: 'Создать тег', exact: true }).click();
  await expect(page.getByLabel('Метаданные', { exact: true })).toBeVisible();
  const creator = page.getByRole('heading', { name: 'Новая операция', exact: true }).locator('..');
  await creator.getByLabel('Счет', { exact: true }).selectOption({ label: 'Исторический EUR · EUR' });
  await creator.getByLabel('Сумма', { exact: true }).fill('1');
  await creator.getByLabel('Дата операции', { exact: true }).fill(dates[1].local);
  await creator.getByLabel('Примечание', { exact: true }).fill('Исторический расход');
  await creator.getByRole('button', { name: 'Сохранить операцию', exact: true }).click();
  await expect(page.locator('.accounts li').filter({hasText: 'Исторический EUR'})).toContainText('99,00 EUR');
  const transferForm = page.getByRole('heading', { name: 'Новый перевод', exact: true }).locator('..');
  await transferForm.getByLabel('Со счета', { exact: true }).selectOption({ label: 'Исторический EUR · EUR' });
  await transferForm.getByLabel('На счет', { exact: true }).selectOption({ label: 'Исторический KWD · KWD' });
  await transferForm.getByLabel('Сумма списания, EUR').fill('3');
  await transferForm.getByLabel('Сумма зачисления, KWD').fill('1,234');
  await transferForm.getByLabel('Добавить комиссию', { exact: true }).check();
  await transferForm.getByLabel('Комиссия, EUR', { exact: true }).fill('0,10');
  await transferForm.getByLabel('Категория комиссии', { exact: true }).selectOption({ label: 'Комиссионные' });
  await transferForm.getByLabel('Описание комиссии', { exact: true }).fill('Комиссия метаданных');
  await transferForm.getByLabel('Тег комиссии Метаданные', { exact: true }).check();
  await transferForm.getByLabel('Дата перевода', { exact: true }).fill(dates[2].local);
  await transferForm.getByLabel('Получатель перевода', { exact: true }).fill('Перевод метаданных');
  await transferForm.getByLabel('Тег перевода Метаданные', { exact: true }).check();
  await transferForm.getByRole('button', { name: 'Сохранить перевод', exact: true }).click();
  await expect(page.locator('.accounts li').filter({hasText: 'Исторический EUR'})).toContainText('95,90 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const accounts = (await (await context.request.get(`${root}/accounts`)).json()).items;
  for (const account of accounts) expect(new Date(account.opened_at).toISOString()).toBe(dates[0].iso);
  const history = (await (await context.request.get(`${root}/transactions`)).json()).items;
  const transfer = history.find((t: {kind: string}) => t.kind === 'transfer');
  const fee = history.find((t: {parent_transaction_id: string | null}) => t.parent_transaction_id === transfer.id);
  const expense = history.find((t: {note: string}) => t.note === 'Исторический расход');
  expect(new Date(expense.occurred_at).toISOString()).toBe(dates[1].iso); expect(new Date(transfer.occurred_at).toISOString()).toBe(dates[2].iso);
  expect(fee.occurred_at).toBe(transfer.occurred_at); expect(fee.tag_ids).toEqual(transfer.tag_ids);
  expect(transfer.rate).toEqual({numerator: '617', denominator: '1500'});
  await page.getByRole('button', { name: 'Изменить тег Метаданные', exact: true }).click();
  await page.getByLabel('Тег в архиве', { exact: true }).check();
  await page.getByRole('button', { name: 'Сохранить тег', exact: true }).click();
  await expect(transferForm.getByLabel('Тег перевода Метаданные', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Изменить категорию Комиссионные', exact: true }).click();
  await page.getByLabel('Категория в архиве').check();
  await page.getByRole('button', { name: 'Сохранить категорию', exact: true }).click();
  await expect(transferForm.getByLabel('Категория комиссии', { exact: true })).toHaveCount(0);
  await page.getByTestId(`transaction-${transfer.id}`).getByRole('button', { name: 'Изменить операцию Перевод метаданных', exact: true }).click();
  const editor = page.getByRole('heading', { name: 'Изменить перевод', exact: true }).locator('..');
  await expect(editor.getByLabel('Тег перевода Метаданные', { exact: true })).toBeChecked();
  await expect(editor.getByLabel('Тег комиссии Метаданные', { exact: true })).toBeChecked();
  await editor.getByLabel('Описание перевода', { exact: true }).fill('Уточнение перевода');
  await editor.getByRole('button', { name: 'Сохранить изменения перевода', exact: true }).click();
  await expect(editor).toHaveCount(0);
  const after = await (await context.request.get(`${root}/transactions/${transfer.id}`)).json();
  const afterFee = await (await context.request.get(`${root}/transactions/${fee.id}`)).json();
  expect(after.occurred_at).toBe(transfer.occurred_at); expect(after.occurred_timezone).toBe(transfer.occurred_timezone);
  expect(after.tag_ids).toEqual(transfer.tag_ids); expect(afterFee.tag_ids).toEqual(fee.tag_ids);
  expect(afterFee.allocations).toEqual(fee.allocations); expect(afterFee.note).toBe(fee.note);
  const accountsAfter = (await (await context.request.get(`${root}/accounts`)).json()).items;
  for (const account of accountsAfter) expect(account.balance_version).toBe(accounts.find((a: {id: string}) => a.id === account.id).balance_version);
  await page.getByRole('button', { name: 'Изменить операцию Исторический расход', exact: true }).click();
  const expenseEditor = page.getByRole('heading', {name: 'Изменить операцию', exact: true}).locator('..');
  await expenseEditor.getByLabel('Дата операции', {exact: true}).fill(dates[2].local);
  await expenseEditor.getByRole('button', {name: 'Сохранить изменения операции', exact: true}).click();
  await expect(expenseEditor).toHaveCount(0);
  const datedExpense = await (await context.request.get(`${root}/transactions/${expense.id}`)).json();
  expect(new Date(datedExpense.occurred_at).toISOString()).toBe(dates[2].iso);
  expect(datedExpense.entries).toEqual(expense.entries);
  await page.getByTestId(`transaction-${transfer.id}`).getByRole('button', { name: 'Изменить операцию Перевод метаданных', exact: true }).click();
  await expect(editor.getByLabel('Описание перевода', {exact: true})).toHaveValue('Уточнение перевода');
  const debit = after.entries.find((e: {amount_minor: string}) => BigInt(e.amount_minor) < 0n);
  const credit = after.entries.find((e: {amount_minor: string}) => BigInt(e.amount_minor) > 0n);
  const concurrent = await context.request.put(`${root}/transactions/${transfer.id}`, {headers: {Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID()}, data: {kind: 'transfer', expected_version: after.version, expected_fee_version: afterFee.version, source_account_id: debit.account_id, target_account_id: credit.account_id, source_amount_minor: (-BigInt(debit.amount_minor)).toString(), target_amount_minor: credit.amount_minor, rate: null, fee: {id: afterFee.id, account_id: afterFee.entries[0].account_id, amount_minor: '10', allocations: afterFee.allocations.map((p: {id: string; category_id: string | null; amount_minor: string}) => ({id: p.id, category_id: p.category_id, amount_minor: p.amount_minor})), note: afterFee.note, tag_ids: afterFee.tag_ids}, occurred_at: after.occurred_at, occurred_timezone: after.occurred_timezone, note: 'Правка перевода другим устройством', payee: after.payee, tag_ids: after.tag_ids} });
  expect(concurrent.status()).toBe(200);
  await editor.getByLabel('Описание перевода', {exact: true}).fill('Моя конфликтующая правка перевода');
  await editor.getByRole('button', {name: 'Сохранить изменения перевода', exact: true}).click();
  const comparison = page.getByRole('heading', {name: 'Конфликт операции', exact: true}).locator('..');
  await expect(comparison).toContainText('Моя конфликтующая правка перевода');
  await expect(comparison).toContainText('Правка перевода другим устройством');
  await expect(comparison).toContainText('Комиссионные');
  await comparison.getByRole('button', {name: 'Загрузить серверную версию в редактор', exact: true}).click();
  await expect(editor.getByLabel('Описание перевода', {exact: true})).toHaveValue('Правка перевода другим устройством');
  await editor.getByRole('button', {name: 'Отменить редактирование', exact: true}).click();
  const preciseID = crypto.randomUUID();
  const precise = await context.request.post(`${root}/transactions`, {headers: {Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id, 'Idempotency-Key': crypto.randomUUID()}, data: {id: preciseID, kind: 'expense', account_id: debit.account_id, amount_minor: '100', occurred_at: dates[1].iso.replace('.123Z', '.123456Z'), occurred_timezone: 'UTC', note: 'Микросекунды', payee: '', tag_ids: [], allocations: [{id: crypto.randomUUID(), category_id: null, amount_minor: '100'}]} });
  expect(precise.status()).toBe(201);
  const preciseBefore = await (await context.request.get(`${root}/transactions/${preciseID}`)).json();
  const balanceBefore = await (await context.request.get(`${root}/accounts/${debit.account_id}`)).json();
  await page.getByRole('button', {name: 'Обновить', exact: true}).click();
  await page.getByRole('button', {name: 'Изменить операцию Микросекунды', exact: true}).click();
  await expenseEditor.getByLabel('Примечание', {exact: true}).fill('Микросекунды сохранены');
  await expenseEditor.getByRole('button', {name: 'Сохранить изменения операции', exact: true}).click();
  await expect(expenseEditor).toHaveCount(0);
  const preciseAfter = await (await context.request.get(`${root}/transactions/${preciseID}`)).json();
  const balanceAfter = await (await context.request.get(`${root}/accounts/${debit.account_id}`)).json();
  expect(preciseBefore.occurred_at).toContain('123456');
  expect(preciseAfter.occurred_at).toBe(preciseBefore.occurred_at);
  expect(preciseAfter.occurred_timezone).toBe('UTC');
  expect(balanceAfter.balance_version).toBe(balanceBefore.balance_version);

});

test('resource conflicts show both values and fit a narrow screen', async ({ page, context }) => {
  await page.setViewportSize({width: 390, height: 844});
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`resources-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  await page.getByLabel('Название счета').fill('Исходное имя');
  await page.getByLabel('Начальный остаток, EUR').fill('100');
  await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
  await expect(page.locator('.accounts')).toContainText('100,00 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const account = (await (await context.request.get(`${root}/accounts`)).json()).items[0];
  const headers = { Origin: 'https://localhost:8444', 'X-CSRF-Token': auth.csrf_token, 'X-Sync-Generation': auth.workspace.sync_generation_id };
  await page.getByRole('button', { name: 'Изменить счет Исходное имя', exact: true }).click();
  await page.getByLabel('Новое название счета').fill('Моя правка счета');
  const concurrent = await context.request.put(`${root}/accounts/${account.id}`, { headers: {...headers, 'Idempotency-Key': crypto.randomUUID()}, data: {expected_version: account.version, name: 'Имя другого устройства', type: 'card', archived: false} });
  expect(concurrent.status()).toBe(200);
  await page.getByRole('button', { name: 'Сохранить счет', exact: true }).click();
  const comparison = page.getByRole('heading', { name: 'Конфликт справочника', exact: true }).locator('..');
  await expect(comparison).toContainText('Моя правка счета');
  await expect(comparison).toContainText('Имя другого устройства');
  await expect(comparison).toContainText('Карта');
  await expect(page.getByLabel('Новое название счета')).toHaveValue('Моя правка счета');
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await comparison.getByRole('button', {name: 'Обновить справочники и закрыть их редакторы', exact: true}).click();
  await expect(comparison).toHaveCount(0);
  await expect(page.getByLabel('Новое название счета')).toHaveCount(0);
  await expect(page.locator('.accounts')).toContainText('Имя другого устройства');
  const currentAccount = await (await context.request.get(`${root}/accounts/${account.id}`)).json();
  expect(currentAccount.balance_version).toBe(account.balance_version);
  await page.getByLabel('Название тега', { exact: true }).fill('Тег');
  await page.getByRole('button', { name: 'Создать тег', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Изменить тег Тег', exact: true })).toBeVisible();
  const tag = (await (await context.request.get(`${root}/tags`)).json()).items[0];
  await page.getByRole('button', { name: 'Изменить тег Тег', exact: true }).click();
  await page.getByLabel('Название тега', { exact: true }).fill('Моя правка тега');
  const scriptName = '<svg onload="window.accountingXss=true">';
  const otherTag = await context.request.put(`${root}/tags/${tag.id}`, { headers: {...headers, 'Idempotency-Key': crypto.randomUUID()}, data: {expected_version: tag.version, name: scriptName, archived: false} });
  expect(otherTag.status()).toBe(200);
  await page.getByRole('button', { name: 'Сохранить тег', exact: true }).click();
  await expect(comparison).toContainText('Моя правка тега');
  await expect(comparison).toContainText(scriptName);
  await expect(page.locator('svg')).toHaveCount(0);
  expect(await page.evaluate(() => Reflect.get(window, 'accountingXss'))).toBeUndefined();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await comparison.getByRole('button', {name: 'Обновить справочники и закрыть их редакторы', exact: true}).click();
  await expect(comparison).toHaveCount(0);
  await expect(page.getByRole('button', {name: `Изменить тег ${scriptName}`, exact: true})).toBeVisible();
});

test('fee refund guards transfer dates until the refund is deleted', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Создать профиль', exact: true }).click();
  await page.getByLabel('Электронная почта').fill(`fee-refund-${crypto.randomUUID()}@example.test`);
  await page.getByLabel('Пароль', { exact: true }).fill('synthetic-browser-password-2026');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible();
  for (const name of ['Источник', 'Получатель']) {
    await page.getByLabel('Название счета').fill(name);
    await page.getByLabel('Начальный остаток, EUR').fill('100');
    await page.getByRole('button', { name: 'Создать счет', exact: true }).click();
    await expect(page.locator('.accounts')).toContainText(name);
  }
  const creator = page.getByRole('heading', {name: 'Новый перевод', exact: true}).locator('..');
  await creator.getByLabel('Со счета', {exact: true}).selectOption({label: 'Источник · EUR'});
  await creator.getByLabel('На счет', {exact: true}).selectOption({label: 'Получатель · EUR'});
  await creator.getByLabel('Сумма списания, EUR').fill('20');
  await creator.getByLabel('Добавить комиссию', {exact: true}).check();
  await creator.getByLabel('Комиссия, EUR', {exact: true}).fill('4');
  await creator.getByRole('button', {name: 'Сохранить перевод', exact: true}).click();
  await expect(page.locator('.accounts li').filter({hasText: 'Источник'})).toContainText('76,00 EUR');
  const auth = await (await context.request.get('/api/v1/auth/session')).json();
  const root = `/api/v1/workspaces/${auth.workspace.id}`;
  const transfer = (await (await context.request.get(`${root}/transactions`)).json()).items.find((t: {kind: string}) => t.kind === 'transfer');
  await page.getByTestId(`transaction-${transfer.fee_transaction_id}`).getByRole('button', {name: `Возврат по операции ${transfer.fee_transaction_id}`, exact: true}).click();
  const refund = page.getByRole('heading', {name: 'Новый возврат', exact: true}).locator('..');
  await refund.getByLabel('Возврат части 1').fill('1');
  await refund.getByLabel('Описание возврата', {exact: true}).fill('Возврат комиссии');
  await refund.getByRole('button', {name: 'Сохранить возврат', exact: true}).click();
  await expect(refund).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({hasText: 'Источник'})).toContainText('77,00 EUR');
  const changedTime = await page.evaluate(instant => { const d = new Date(new Date(instant).getTime() + 1), two = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${two(d.getMonth() + 1)}-${two(d.getDate())}T${two(d.getHours())}:${two(d.getMinutes())}:${two(d.getSeconds())}.${String(d.getMilliseconds()).padStart(3, '0')}`; }, transfer.occurred_at);
  await page.getByTestId(`transaction-${transfer.id}`).getByRole('button', {name: `Изменить операцию ${transfer.id}`, exact: true}).click();
  const editor = page.getByRole('heading', {name: 'Изменить перевод', exact: true}).locator('..');
  await editor.getByLabel('Дата перевода', {exact: true}).fill(changedTime);
  await editor.getByRole('button', {name: 'Сохранить изменения перевода', exact: true}).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  expect((await (await context.request.get(`${root}/transactions/${transfer.id}`)).json()).occurred_at).toBe(transfer.occurred_at);
  await editor.getByLabel('Добавить комиссию', {exact: true}).uncheck();
  await editor.getByRole('button', {name: 'Сохранить изменения перевода', exact: true}).click();
  await expect(page.getByRole('alert')).toContainText('Конфликт');
  await expect(page.locator('.accounts li').filter({hasText: 'Источник'})).toContainText('77,00 EUR');
  await page.getByRole('button', {name: 'Удалить операцию Возврат комиссии', exact: true}).click();
  await page.getByRole('button', {name: 'Подтвердить удаление операции', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'Удаление операции', exact: true})).toHaveCount(0);
  await expect(page.locator('.accounts li').filter({hasText: 'Источник'})).toContainText('76,00 EUR');
  await page.getByTestId(`transaction-${transfer.id}`).getByRole('button', {name: `Изменить операцию ${transfer.id}`, exact: true}).click();
  await editor.getByLabel('Дата перевода', {exact: true}).fill(changedTime);
  await editor.getByRole('button', {name: 'Сохранить изменения перевода', exact: true}).click();
  await expect(editor).toHaveCount(0);
  const final = await (await context.request.get(`${root}/transactions/${transfer.id}`)).json();
  const fee = await (await context.request.get(`${root}/transactions/${transfer.fee_transaction_id}`)).json();
  expect(new Date(final.occurred_at).getTime()).toBe(new Date(transfer.occurred_at).getTime() + 1);
  expect(fee.occurred_at).toBe(final.occurred_at);
});
